### ISSUE TITLE
[FEATURE] - upgraded elector example using gocron-v2

### ISSUE THREAD

**Issue by seriouspoop** [go-co-op/gocron-etcd-elector#24]
### Is your feature request related to a problem? Please describe

I was struggling to find a example for using `gocron-etcd-elector`, never understood how to make it work with multiple instances of an application.

### Describe the solution you'd like

I have written a new and better example which shows the use of replica instances and etcd cluster, and a live view of leader election in docker logs like in a production environment.

### Describe alternatives you've considered

NA

### Additional context

NA

**Comment by JohnRoesler** [comment]
> I have written a new and better example which shows the use of replica instances and etcd cluster, and a live view of leader election in docker logs like in a production environment.

@seriouspoop could you share that example?

**Comment by seriouspoop** [comment]
@JohnRoesler yeah here you go, https://github.com/seriouspoop/gocron-etcd-elector-example

**Comment by JohnRoesler** [comment]
Would you like to PR this in to the `example` directory? Or reference it by link to your repo? Happy to have a solid example included, and happy to include it however you'd like
